//anything written here will be shared by all the pages in the project. 
//all pages will be the children which gets called here in the function


// the pages dont rerender when the route changes, so if you have any functionalities of rerendering.. then use
// template.js which is similar to layout, where it rerenders everytime route changes

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Learning Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <main className="px-8 py-30 max-w-6xl mx-auto">
        {children}
        </main>
      </body>
    </html>
  );
}
